services:
  db:
    image: postgres:16
    container_name: hotel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hotelaria
    ports:
      - "5000:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data

volumes:
  hotel-db-data:
