services:
  db:
    image: postgres
    container_name: hotel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: hotelaria
    ports:
      - "5432:5432"