"""init

Revision ID: 216f4e56ef08
Revises: 
Create Date: 2026-04-20 11:42:45.008894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216f4e56ef08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('produtos_servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('preco_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.Enum('PRODUTO', 'SERVICO', name='categoriaitem'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('tipos_quarto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('precoBaseDiaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('GERENTE', 'RECEPCIONISTA', name='tipousuario'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('quartos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('andar', sa.Integer(), nullable=False),
    sa.Column('status_ocupacao', sa.Enum('LIVRE', 'OCUPADO', 'MANUTENCAO', name='statusocupacao'), nullable=False),
    sa.Column('status_limpeza', sa.Enum('LIMPO', 'SUJO', name='statuslimpeza'), nullable=False),
    sa.Column('tipo_quarto_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_quarto_id'], ['tipos_quarto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_quarto_id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('valor_total_previsto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', 'LISTA_ESPERA', 'UTILIZADA', name='statusreserva'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospedagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('quarto_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('data_checkin', sa.DateTime(), nullable=False),
    sa.Column('data_checkout_previsto', sa.DateTime(), nullable=False),
    sa.Column('data_checkout_real', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'FINALIZADA', 'CANCELADA', name='statushospedagem'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_consumo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospedagem_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_consumo')
    op.drop_table('hospedagens')
    op.drop_table('reservas')
    op.drop_table('quartos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tipos_quarto')
    op.drop_table('produtos_servicos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
