"""tabela_quartos_sync2

Revision ID: 37f852613cb5
Revises: b4e3d2b7bcb5
Create Date: 2026-03-04 16:11:14.608999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f852613cb5'
down_revision: Union[str, Sequence[str], None] = 'b4e3d2b7bcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quartos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('andar', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LIVRE', 'OCUPADO', 'SUJO', 'MANUTENCAO', name='statusquarto'), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quartos')
    # ### end Alembic commands ###
