"""adiciona tabela Item Consumo

Revision ID: 41b67472390d
Revises: ef6615024c82
Create Date: 2026-03-23 08:46:58.753042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b67472390d'
down_revision: Union[str, Sequence[str], None] = 'ef6615024c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_consumo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hospedagem_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_consumo')
    # ### end Alembic commands ###
