"""adiciona tabela Produto Servico

Revision ID: c1a438c6dcf0
Revises: 41b67472390d
Create Date: 2026-03-23 11:00:21.624793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a438c6dcf0'
down_revision: Union[str, Sequence[str], None] = '41b67472390d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_servicos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('preco_padrao', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('categoria', sa.Enum('PRODUTO', 'SERVICO', name='categoriaitem'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos_servicos')
    # ### end Alembic commands ###
