"""adiciona tabela tipo_quarto

Revision ID: e0f413bc8055
Revises: d42394c24b72
Create Date: 2026-03-16 14:07:49.889565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f413bc8055'
down_revision: Union[str, Sequence[str], None] = 'd42394c24b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_quarto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('precoBaseDiaria', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacidade', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_quarto_id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=False),
    sa.Column('data_saida', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('valor_total_previsto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMADA', 'CANCELADA', 'LISTA_ESPERA', 'UTILIZADA', name='statusreserva'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quartos', sa.Column('tipo_quarto_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quartos', 'tipos_quarto', ['tipo_quarto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quartos', type_='foreignkey')
    op.drop_column('quartos', 'tipo_quarto_id')
    op.drop_table('reservas')
    op.drop_table('tipos_quarto')
    # ### end Alembic commands ###
