"""adiciona tabela Hospedagem

Revision ID: ef6615024c82
Revises: e0f413bc8055
Create Date: 2026-03-18 10:59:40.091905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef6615024c82'
down_revision: Union[str, Sequence[str], None] = 'e0f413bc8055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospedagens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('quarto_id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=True),
    sa.Column('data_checkin', sa.DateTime(), nullable=False),
    sa.Column('data_checkout_previsto', sa.DateTime(), nullable=False),
    sa.Column('data_checkout_real', sa.DateTime(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'FINALIZADA', 'CANCELADA', name='statushospedagem'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['quarto_id'], ['quartos.id'], ),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospedagens')
    # ### end Alembic commands ###
